export const FETCH_TASKS_LOADING = "FETCH_TASKS_LOADING"
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS"
export const FETCH_TASKS_FAILURE = "FETCH_TASKS_FAILURE"

export const ADD_TASK = "ADD_TASK"
export const DELETE_TASK = "DELETE_TASK"
export const UPDATE_TASK = "UPDATE_TASK"
